php_ini_settings:
  - option: "memory_limit"
    value: "128M"
  - option: "post_max_size"
    value: "8M"
  - option: "upload_max_filesize"
    value: "2M"
  - option: "display_error"
    value: "On"
  - option: "error_reporting"
    value: "E_ALL | E_STRICT"
  - option: "display_startup_errors"
    value: "On"
  - option: "html_errors"
    value: "On"
  - option: "track_errors"
    value: "On"