- name: Agregando repositorio ppa oficial de NginX 
  apt_repository: >
    repo="ppa:nginx/stable"
    update_cache=yes

- name: Instalando NginX-full
  apt: >
    name=nginx-full
    state=latest

- name: Agregando template personalizado de nginx.conf
  template: >
    src=nginx.conf.j2
    dest=/etc/nginx/nginx.conf
    validate="nginx -t -c %s"
  notify: reload nginx

- name: Habilitar NginX cada reinicio
  service: >
    name=nginx
    state=started
    enabled=yes